server:
  port: 8080
spring:
  application:
    name: riskcontroll
  datasource:
    name: wangsc
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/grabyou?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password:
  devtools:
    restart:
      enabled: true
      additional-paths: src/java/main
      exclude: static/**,public/**,WEB-INF/**
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: wangsc.riskcontroll.entity

## 热部署生效
#spring.devtools.restart.enabled=true
## 设置需要重启的目录
#spring.devtools.restart.additional-paths=src/java/main
## 设置不需要重启的目录
#spring.devtools.restart.exclude=static/**,public/**,WEB-INF/**